all:
	g++ -o render render_main.cpp Color.cpp DepthCue.cpp DirectionalLight.cpp Light.cpp Material.cpp Point3.cpp PointLight.cpp Ray.cpp Scene.cpp SceneObject.cpp Sphere.cpp Vector3.cpp ViewWindow.cpp